export enum EPreferredRole {
  TEAM_LEADER = "TEAM_LEADER",
  DESIGNER = "DESIGNER",
  FRONTEND = "FRONTEND",
  BACKEND = "BACKEND",
  BUSINESS_ANALYST = "BUSINESS_ANALYST",
  TESTER = "TESTER",
  ARCHITECT = "ARCHITECT",
  DEVOPS = "DEVOPS",
}

export enum ESkills {
  JAVASCRIPT = "JAVASCRIPT",
  TYPESCRIPT = "TYPESCRIPT",
  JAVA = "JAVA",
  C = "C",
  UI_UX = "UI_UX",
  SQL = "SQL",
}
